server.port=8081
spring.application.name=provider-node
spring.datasource.url=${GAIAX_DB_URL:jdbc:postgresql://localhost:5432/gaiax_health}
spring.datasource.username=${GAIAX_DB_USER:gaiax}
spring.datasource.password=${GAIAX_DB_PASSWORD:gaiax}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:init_db.sql
spring.jpa.hibernate.ddl-auto=update
