spring.application.name=tfg-enrique-mora-gaia-x
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.probes.enabled=true
gaiax.trust.base-url=${GAIAX_TRUST_BASE_URL:http://localhost:8082}
